---
image: python:3.7

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install pylint flake8

stages:
  - linting

flake8:
  stage: linting
  script:
    - flake8 python-gitlab-api/*.py

pylint:
  stage: linting
  script:
    - pylint python-gitlab-api/*.py
