---
image: python:3.7

before_script:
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install pylint flake8

stages:
  - linting

flake8:
  stage: linting
  script:
    - flake8 gitlab_api/

pylint:
  stage: linting
  script:
    - pylint gitlab_api/
